### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Itai-Nelken** [techcoder20/PiAppsPackageManagerTerminal#2]
first of all your script works great!
the suggestion:
to install vscodium for example, I have to run this command: `./papm.sh install VSCodium` if I put `vscodium` or `VScodium` it won't work. my suggestion is to make all app names lowercase only using a script like this one I made:
```bash
#!/bin/bash

if [[ $1 == "install" ]] && [[ $2 == "vscodium" ]]; then
	~/pi-apps/manage install VSCodium
fi
```
and make one like that for each app.

there probably is a better way of doing that that doesn't require adding a new if/then/else argument (I think thats how you say it) every time a new app is added to pi-apps.

**Comment by techcoder20** [comment]
The script uses python now. The idea is good but we will have to implement it for every single apps. to deal with this i have created a search and list argument so that they dont make a mistake in the name.
