### ISSUE TITLE
Simples others commands

### ISSUE THREAD

**Issue by pi-dev500** [techcoder20/PiAppsPackageManagerTerminal#3]
@techcoder20 Can you add info command and permit to install pi-apps packages that are stored into zipfile?

**Comment by techcoder20** [comment]
Why do you want it to detect the app if it's in a zip file ? If u do need it to get detected can't you extract it in the apps folder ?

**Comment by pi-dev500** [comment]
I think that can be helpful for beginners and the users that havent pi-apps

**Comment by Itai-Nelken** [comment]
extracting the zip into `~/pi-apps/apps` isn't that hard.
maybe something better will be to add instructions on how to add apps to the help.
